### ISSUE TITLE
[Epic]: Front-end implementation

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/constitution-checker#7]
### Acknowledgements

- [X] I am a member of the team

### Epic description

UI/UX design for the Front end in Figma.
Front end implementation

### Acceptance criteria (Main list)
- [x] UI/UX is designed in Figma
    - [x] Design has been agreed by stakeholders
    - [x] Main user journeys: Inputs, Outputs, Checks
    - [x] Logo
- [x] User inputs
    - [x] Users can upload their json proposals
    - [x] Users can fill a form for their proposals
    - [x] Form is prefilled with current values or proposal values
    - [x] Users can edit their proposals from the form itself
    - [x] Users can provide a URL to a proposal json
    - [x] Users can provide a Transaction ID (on SanchoNet)
    - [x] Users can revert to their initial proposal (or current values) after modifications
- [x] User outputs
    - [x] Users can see the result of their proposal on the guardrails
    - [x] Users can identify guardrails that failed
    - [x] Users can identify guardrails that succeeded
    - [x] Users can identify guardrails that are not yet checked
    - [x] Users can download the last checked proposal
    - [x] Users can download a report of the checked guardrails attached to their proposals (signed PDF?)
- [x] Front end is released online

### Additional stories

- [x] #8
- [x] #10 
- [x] #32
- [x] #11 

### Priority

Medium

### Story points

100

**Comment by RSoulatIOHK** [comment]
- [x] Ask Mike about this.

**Comment by RSoulatIOHK** [comment]
@KJES4 Should we mark it as done?
